version: '2'
services:

  poc-sqs-web:
    build: ../../web
    image: quay.io/turner/poc-sqs-web:1.0.0-${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}
    ports:
     - "80:5000"
    environment:
      PORT: 5000
      HEALTHCHECK: /
      SQS_QUEUE: ${SQS_QUEUE}
      REGION: ${REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID} 
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY} 
  
  poc-sqs-worker:
    build: ../../worker
    image: quay.io/turner/poc-sqs-worker:1.0.0-${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}
    ports:
     - "81:6000"
    environment:
      PORT: 6000
      HEALTHCHECK: /
      SQS_QUEUE: ${SQS_QUEUE}
      REGION: ${REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID} 
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}